require("exoess.plugins-setup")
require("exoess.core.options")
require("exoess.core.keymaps")
require("exoess.core.colorscheme")
require("exoess.plugins.nvim-tree")
require("exoess.plugins.lualine")
require("exoess.plugins.colorizer")
require("exoess.plugins.barbar")
